spring:
  application:
    name: spring-azure-mail
microsoft:
  azure:
    client-id: ${AZURE_CLIENT_ID:}
    client-secret: ${AZURE_CLIENT_SECRET:}
    tenant-id: ${AZURE_TENANT_ID:}
    scope: ${AZURE_SCOPE:}